In [1]:
### Decision Trees ###
# https://www.youtube.com/watch?v=tNa99PG8hR8
# https://scikit-learn.org/stable/modules/tree.html

import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

In [20]:
# 1. Import dataset:
iris = load_iris()
print (iris.feature_names)
print (iris.target_names)
print (iris.data[0])
print (iris.target[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[4.9 3.  1.4 0.2]
0


In [3]:
test_idx = [0,50,100]

In [4]:
# 1.1. Training data:
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

In [5]:
# 1.2. Testing data:
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [6]:
# 2. Train the classifier:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(train_data, train_target)

In [7]:
# 3. Predict label for new flower:
print (test_target)
print (clf.predict(test_data))

[0 1 2]
[0 1 2]


In [9]:
# 4. Graph the tree:
import graphviz
dot_data = tree.export_graphviz(clf, out_file=None)
graph = graphviz.Source(dot_data)
graph.render("iris")

'iris.pdf'

In [13]:
dot_data = tree.export_graphviz(clf, out_file=None, 
                      feature_names=iris.feature_names,  
                      class_names=iris.target_names,  
                      filled=True, rounded=True,  
                      special_characters=True)  
graph = graphviz.Source(dot_data)  
graph.render("iris.color") 

'iris.color.pdf'

In [16]:
# 5. Test the data in the modeled tree:
print (test_data[1], test_target[1])
print (iris.feature_names, iris.target_names)

[7.  3.2 4.7 1.4] 1
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']


In [17]:
dot_data = tree.export_graphviz(clf, out_file=None, 
                      feature_names=iris.feature_names,  
                      class_names=iris.target_names,  
                      filled=True, rounded=True,  
                      special_characters=True)  
graph = graphviz.Source(dot_data)  
graph.render("iris.color.test") 

'iris.color.test.pdf'